plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    // Consumes the profile generated by :baselineprofile and bakes it into the
    // release APK so profileinstaller can AOT-compile hot paths on first run.
    alias(libs.plugins.androidx.baselineprofile)
    alias(libs.plugins.google.services) apply false
}

if (file("google-services.json").isFile) {
    apply(plugin = "com.google.gms.google-services")
}

val siloVersionName = providers
    .gradleProperty("siloVersionName")
    .orElse(providers.environmentVariable("SILO_VERSION_NAME"))
    // Release builds override this from the validated Git tag in
    // android-build.yml. Keep local/dev builds aligned with the latest release.
    .orElse("0.3.11")

val siloVersionCode = providers
    .gradleProperty("siloVersionCode")
    .orElse(providers.environmentVariable("SILO_VERSION_CODE"))
    .map { value ->
        val code = value.toIntOrNull() ?: error("siloVersionCode must be an integer.")
        require(code > 0) { "siloVersionCode must be positive." }
        // The *2 (+1 for TV) form-factor multiplier applied at versionCode
        // assignment must stay under Google Play's 2_100_000_000 ceiling.
        require(code <= 1_049_999_999) {
            "siloVersionCode must be <= 1_049_999_999 so the form-factor multiplier " +
                "keeps both artifacts under Google Play's 2_100_000_000 versionCode limit."
        }
        code
    }
    // Bump this per release. base -> phone = base*2, TV = base*2+1. base 6 was
    // the 12/13 build; base 7 -> phone 14, TV 15.
    .orElse(7)

// APK ABI splits (below) are incompatible with the App Bundle build:
// PerModuleBundleTask.getResourcesFile() expects a single processed-resources
// file and throws "Sequence contains more than one matching element" when the
// splits produce one per ABI. The bundle does its own ABI splitting via the
// `bundle { abi }` block, so disable APK splits whenever a bundle task is run.
val isBuildingBundle = gradle.startParameter.taskNames.any {
    it.contains("bundle", ignoreCase = true)
}

kotlin {
    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = "21"
            }
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(project(":shared"))
            implementation(project(":android-shared"))
            implementation(libs.kotlinx.serialization.json)
            implementation(compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(libs.activity.compose)
            implementation(libs.lifecycle.runtime.compose)
            implementation(libs.lifecycle.viewmodel.compose)
            implementation(libs.lifecycle.process)
            implementation(libs.navigation.compose)
            implementation(libs.koin.android)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)
            implementation(libs.coil.compose)
            implementation(libs.coil.network.ktor)
            implementation(libs.jsoup)
            implementation(libs.media3.exoplayer)
            implementation(libs.media3.exoplayer.hls)
            implementation(libs.media3.datasource.okhttp)
            implementation(libs.media3.ui)
            implementation(libs.media3.session)
            implementation(libs.media3.common.ktx)
            implementation(libs.media3.ui.compose)
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.androidx.work.runtime.ktx)
            implementation(libs.androidx.webkit)
            implementation(libs.koin.androidx.workmanager)
            implementation(libs.firebase.messaging)
            // Google Cast (Chromecast) — phone app only. TV app must not depend
            // on this; it uses the separate NSD/mDNS SiloCast device-remote.
            implementation(libs.play.services.cast.framework)
            implementation(libs.androidx.mediarouter)
            implementation("androidx.palette:palette-ktx:1.0.0")
            // Installs the Baseline Profile (generated by :baselineprofile) into the
            // app at first run so hot paths are AOT-compiled — faster cold start.
            implementation(libs.androidx.profileinstaller)
        }

        androidUnitTest.dependencies {
            implementation(kotlin("test"))
            implementation(kotlin("test-junit"))
            // NotificationRow's `reason_flags` default arg is a kotlinx JsonObject;
            // constructing it in unit tests needs the json artifact on the test
            // classpath (the :shared dep is `implementation`, so it isn't transitive).
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.ktor.client.mock)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.json)
            // AdminEntryViewModelTest drives a viewModelScope coroutine, so it
            // needs the test dispatcher / runTest helpers on the test classpath.
            implementation(libs.kotlinx.coroutines.test)
            // WatchTogetherEntryDestinationTest asserts on real Route.route
            // strings, which call android.net.Uri.encode — Robolectric supplies
            // the real Android impl under plain JVM unit tests.
            implementation(libs.robolectric)
            // ReflowBridgeTest uses org.json directly in plain JVM unit tests.
            // The Android-bundled org.json is mocked; this standalone jar provides
            // the real implementation so tests don't need the Robolectric runner.
            implementation("org.json:json:20240303")
            // ReaderViewModelReaderTargetSourceTest resolves offline media through
            // the Room-backed DownloadMetadataStore, so it builds an in-memory
            // SiloDatabase. :android-shared exposes Room as `implementation`, so the
            // runtime + ApplicationProvider aren't transitive — add them here.
            implementation(libs.androidx.room.runtime)
            implementation(libs.androidx.test.core)
        }
    }
}

android {
    val allowDebugReleaseSigning = providers
        .gradleProperty("allowDebugReleaseSigning")
        .orElse(providers.environmentVariable("ALLOW_DEBUG_RELEASE_SIGNING"))
        .map(String::toBoolean)
        .getOrElse(false)

    namespace = "org.siloserver.silo.android"
    compileSdk = 36
    defaultConfig {
        applicationId = "org.siloserver.silo"
        minSdk = 24
        targetSdk = 36
        // Shares one Play listing with the TV app (same applicationId). Two
        // artifacts under one listing need distinct versionCodes: phone =
        // base*2, TV = base*2+1, so each release bumps both by 2 with no reuse.
        versionCode = siloVersionCode.get() * 2
        versionName = siloVersionName.get()
        // Shadow the android-shared BuildConfig field so per-app flavors
        // (e.g., a "no-FFmpeg" sideload build for size-constrained QA) can
        // override without rebuilding the shared module. The runtime reads
        // the android-shared value — this field is reserved for future
        // flavor wiring.
        buildConfigField("boolean", "FFMPEG_AUDIO_ENABLED", "true")
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }
    // Release signing comes from the environment (CI decodes the keystore from
    // a GitHub secret). Local release builds without these vars fall back to
    // the debug-signing opt-in below, or stay unsigned.
    val releaseKeystorePath = providers.environmentVariable("SILO_RELEASE_KEYSTORE").orNull
    val hasReleaseSigning = !releaseKeystorePath.isNullOrBlank()
    signingConfigs {
        if (hasReleaseSigning) {
            create("release") {
                storeFile = file(releaseKeystorePath!!)
                storePassword = providers.environmentVariable("SILO_RELEASE_KEYSTORE_PASSWORD").orNull
                keyAlias = providers.environmentVariable("SILO_RELEASE_KEY_ALIAS").orNull
                // The key password may differ from the keystore password; fall
                // back to the keystore password when they're the same.
                keyPassword = providers.environmentVariable("SILO_RELEASE_KEY_PASSWORD").orNull
                    ?.takeIf { it.isNotBlank() }
                    ?: providers.environmentVariable("SILO_RELEASE_KEYSTORE_PASSWORD").orNull
            }
        }
    }
    buildTypes {
        release {
            // Launch-prep: full R8 + resource shrinking. Keep rules for this
            // reflection/JNI-heavy stack live in the shared root proguard-rules.pro
            // (Koin, kotlinx.serialization, Media3 FFmpeg, BouncyCastle,
            // Room, Coil3, zxing, Ktor). R8 breakage is runtime-only, so a minified
            // install must be smoke-tested on device before shipping.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                rootProject.file("proguard-rules.pro"),
            )
            if (hasReleaseSigning) {
                signingConfig = signingConfigs.getByName("release")
            } else if (allowDebugReleaseSigning) {
                // Debug-sign release builds for local smoke tests when
                // explicitly opted in and no release keystore is available.
                signingConfig = signingConfigs.getByName("debug")
            }
        }
    }
    // Play Store App Bundle: enable per-ABI splits so Play serves a device
    // only the native libs it can run. Relevant once we ship the FFmpeg
    // AAR — the universal APK carries all three ABIs (~3 MB of native
    // libs); ABI-split bundles drop that to ~1 MB per device.
    bundle {
        abi {
            enableSplit = true
        }
    }
    // Per-ABI APKs for sideload QA (one per arch + a universal). Matches
    // the device-matrix QA procedure in
    // docs/plans/ffmpeg-audio-extension-plan.md Phase 4. `isUniversalApk`
    // keeps the all-ABIs APK around for dev convenience.
    splits {
        abi {
            // Off for bundle builds (see isBuildingBundle) — the AAB handles
            // per-ABI delivery itself and APK splits break its resource step.
            isEnable = !isBuildingBundle
            reset()
            include("arm64-v8a", "armeabi-v7a", "x86_64")
            isUniversalApk = true
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
        isCoreLibraryDesugaringEnabled = true
    }
    testOptions {
        unitTests {
            isIncludeAndroidResources = true
        }
    }
    packaging {
        resources {
            // BouncyCastle (bcprov/bctls/bcutil, pulled in via android-shared's
            // LAN-pairing engine) + jspecify each ship this OSGi multi-release
            // stub; drop the duplicates so the APK packages.
            excludes += "/META-INF/versions/*/OSGI-INF/MANIFEST.MF"
        }
    }
}

dependencies {
    coreLibraryDesugaring(libs.desugar.jdk.libs)
    // The generated Baseline Profile artifact (see :baselineprofile).
    baselineProfile(project(":baselineprofile"))
}
