// Code generated by cmd/settingsgen from contracts/settings/v1/manifest.json. DO NOT EDIT.
//
// Regenerate with: make settings-bindings
//
// Every key, type, scope and default here comes from the manifest, so a client
// cannot drift from the server's contract by editing a constant. Adding a setting
// is a manifest change plus a regeneration, never a hand-written key.

package org.siloserver.silo.model.settings

data class SettingSuggestedOption(
    val value: String,
    val introducedIn: Int,
)

data class SettingOptionSet(
    val type: String,
    val options: List<SettingSuggestedOption>,
)

data class SettingPresentation(
    val suggestedOptions: String? = null,
    val unsetLabel: String? = null,
)

object SettingKeys {
    const val REVISION = 7

    /** Metadata language */
    const val CATALOG_METADATA_LANGUAGE = "catalog.metadata_language"
    /** Metadata language exceptions */
    const val CATALOG_METADATA_LANGUAGE_OVERRIDES = "catalog.metadata_language_overrides"
    /** Download quality */
    const val DOWNLOADS_DEFAULT_QUALITY = "downloads.default_quality"
    /** Keep watched downloads */
    const val DOWNLOADS_KEEP_WATCHED = "downloads.keep_watched"
    /** Download over Wi-Fi only */
    const val DOWNLOADS_WIFI_ONLY = "downloads.wifi_only"
    /** Primary menu */
    const val NAV_PRIMARY_MENU = "nav.primary_menu"
    /** Navigation shortcuts */
    const val NAV_SHORTCUTS = "nav.shortcuts"
    /** Show audiobooks */
    const val NAV_SHOW_AUDIOBOOKS = "nav.show_audiobooks"
    /** Preferred audio language */
    const val PLAYBACK_AUDIO_LANGUAGE = "playback.audio_language"
    /** Auto-play next episode */
    const val PLAYBACK_AUTO_PLAY_NEXT = "playback.auto_play_next"
    /** Preview next episode */
    const val PLAYBACK_AUTO_PLAY_NEXT_PREVIEW = "playback.auto_play_next_preview"
    /** Auto-skip credits */
    const val PLAYBACK_AUTO_SKIP_CREDITS = "playback.auto_skip_credits"
    /** Auto-skip intros */
    const val PLAYBACK_AUTO_SKIP_INTRO = "playback.auto_skip_intro"
    /** Auto-skip recaps */
    const val PLAYBACK_AUTO_SKIP_RECAP = "playback.auto_skip_recap"
    /** Skip intros */
    const val PLAYBACK_INTRO_SKIP_MODE = "playback.intro_skip_mode"
    /** Maximum bitrate */
    const val PLAYBACK_MAX_BITRATE_KBPS = "playback.max_bitrate_kbps"
    /** Next up prompt */
    const val PLAYBACK_NEXT_UP_PROMPT_SECONDS = "playback.next_up_prompt_seconds"
    /** Preferred quality */
    const val PLAYBACK_PREFERRED_QUALITY = "playback.preferred_quality"
    /** Show forced subtitles */
    const val PLAYBACK_SHOW_FORCED_SUBTITLES = "playback.show_forced_subtitles"
    /** Subtitle appearance */
    const val PLAYBACK_SUBTITLE_APPEARANCE = "playback.subtitle_appearance"
    /** Preferred subtitle language */
    const val PLAYBACK_SUBTITLE_LANGUAGE = "playback.subtitle_language"
    /** Subtitles */
    const val PLAYBACK_SUBTITLE_MODE = "playback.subtitle_mode"
    /** Audio sync offset */
    const val PLAYER_AUDIO_SYNC_MS = "player.audio_sync_ms"
    /** Dolby Vision */
    const val PLAYER_DOLBY_VISION_ENABLED = "player.dolby_vision_enabled"
    /** Dolby Vision Profile 7 fallback */
    const val PLAYER_DV_PROFILE7_HDR10_FALLBACK = "player.dv_profile7_hdr10_fallback"
    /** HDR */
    const val PLAYER_HDR_ENABLED = "player.hdr_enabled"
    /** Match content frame rate */
    const val PLAYER_MATCH_FRAME_RATE = "player.match_frame_rate"
    /** Screen orientation */
    const val PLAYER_ORIENTATION_MODE = "player.orientation_mode"
    /** Still watching prompt */
    const val PLAYER_PASSOUT_THRESHOLD = "player.passout_threshold"
    /** Picture in picture */
    const val PLAYER_PICTURE_IN_PICTURE_ENABLED = "player.picture_in_picture_enabled"
    /** Playback speed */
    const val PLAYER_PLAYBACK_SPEED = "player.playback_speed"
    /** Rewind on resume */
    const val PLAYER_RESUME_REWIND_SECONDS = "player.resume_rewind_seconds"
    /** Seek cache */
    const val PLAYER_SEEK_CACHE_ENABLED = "player.seek_cache_enabled"
    /** Default sleep timer */
    const val PLAYER_SLEEP_TIMER_DEFAULT_MINUTES = "player.sleep_timer_default_minutes"
    /** Subtitle sync offset */
    const val PLAYER_SUBTITLE_SYNC_MS = "player.subtitle_sync_ms"
    /** Video sizing */
    const val PLAYER_VIDEO_GRAVITY = "player.video_gravity"
    /** Search scope */
    const val SEARCH_MEDIA_SCOPE = "search.media_scope"
    /** Match device caption settings */
    const val SUBTITLE_MATCHES_DEVICE = "subtitle.matches_device"
    /** Poster badges */
    const val UI_CARD_OVERLAYS = "ui.card_overlays"
    /** Media cards */
    const val UI_CARD_PRESENTATION = "ui.card_presentation"
    /** Custom CSS */
    const val UI_CUSTOM_CSS = "ui.custom_css"
    /** Custom theme variables */
    const val UI_CUSTOM_THEME_VARS = "ui.custom_theme_vars"
    /** Date format */
    const val UI_DATE_FORMAT = "ui.date_format"
    /** Hidden libraries */
    const val UI_DISABLED_LIBRARY_IDS = "ui.disabled_library_ids"
    /** High contrast */
    const val UI_HIGH_CONTRAST = "ui.high_contrast"
    /** Library order */
    const val UI_LIBRARY_ORDER = "ui.library_order"
    /** Remembered library view */
    const val UI_LIBRARY_PAGE_STATE = "ui.library_page_state"
    /** Next up episodes */
    const val UI_NEXT_UP_MODE = "ui.next_up_mode"
    /** Remember library view */
    const val UI_REMEMBER_LIBRARY_PAGE_STATE = "ui.remember_library_page_state"
    /** Pinned sidebar items */
    const val UI_SIDEBAR_PINS = "ui.sidebar_pins"
    /** Text size */
    const val UI_TEXT_SCALE = "ui.text_scale"
    /** Text weight */
    const val UI_TEXT_WEIGHT = "ui.text_weight"
    /** Theme */
    const val UI_THEME = "ui.theme"
    /** Time format */
    const val UI_TIME_FORMAT = "ui.time_format"

    /** Every key the server stores. Safe to flush. */
    val REMOTE: List<String> = listOf(
        CATALOG_METADATA_LANGUAGE,
        CATALOG_METADATA_LANGUAGE_OVERRIDES,
        NAV_PRIMARY_MENU,
        NAV_SHORTCUTS,
        PLAYBACK_AUDIO_LANGUAGE,
        PLAYBACK_AUTO_PLAY_NEXT,
        PLAYBACK_AUTO_PLAY_NEXT_PREVIEW,
        PLAYBACK_AUTO_SKIP_CREDITS,
        PLAYBACK_AUTO_SKIP_INTRO,
        PLAYBACK_AUTO_SKIP_RECAP,
        PLAYBACK_INTRO_SKIP_MODE,
        PLAYBACK_MAX_BITRATE_KBPS,
        PLAYBACK_NEXT_UP_PROMPT_SECONDS,
        PLAYBACK_PREFERRED_QUALITY,
        PLAYBACK_SHOW_FORCED_SUBTITLES,
        PLAYBACK_SUBTITLE_APPEARANCE,
        PLAYBACK_SUBTITLE_LANGUAGE,
        PLAYBACK_SUBTITLE_MODE,
        PLAYER_AUDIO_SYNC_MS,
        PLAYER_DOLBY_VISION_ENABLED,
        PLAYER_DV_PROFILE7_HDR10_FALLBACK,
        PLAYER_HDR_ENABLED,
        PLAYER_MATCH_FRAME_RATE,
        PLAYER_ORIENTATION_MODE,
        PLAYER_PLAYBACK_SPEED,
        PLAYER_SEEK_CACHE_ENABLED,
        PLAYER_SLEEP_TIMER_DEFAULT_MINUTES,
        PLAYER_SUBTITLE_SYNC_MS,
        PLAYER_VIDEO_GRAVITY,
        SEARCH_MEDIA_SCOPE,
        UI_CARD_OVERLAYS,
        UI_CARD_PRESENTATION,
        UI_CUSTOM_CSS,
        UI_CUSTOM_THEME_VARS,
        UI_DATE_FORMAT,
        UI_DISABLED_LIBRARY_IDS,
        UI_HIGH_CONTRAST,
        UI_LIBRARY_ORDER,
        UI_LIBRARY_PAGE_STATE,
        UI_NEXT_UP_MODE,
        UI_REMEMBER_LIBRARY_PAGE_STATE,
        UI_SIDEBAR_PINS,
        UI_TEXT_SCALE,
        UI_TEXT_WEIGHT,
        UI_THEME,
        UI_TIME_FORMAT,
    )

    /** Contract-known keys that never leave the device. */
    val CLIENT_LOCAL: List<String> = listOf(
        DOWNLOADS_DEFAULT_QUALITY,
        DOWNLOADS_KEEP_WATCHED,
        DOWNLOADS_WIFI_ONLY,
        NAV_SHOW_AUDIOBOOKS,
        PLAYER_PASSOUT_THRESHOLD,
        PLAYER_PICTURE_IN_PICTURE_ENABLED,
        PLAYER_RESUME_REWIND_SECONDS,
        SUBTITLE_MATCHES_DEVICE,
    )

    val BOOLEAN_KEYS: Set<String> = setOf(
        PLAYBACK_AUTO_PLAY_NEXT,
        PLAYBACK_AUTO_PLAY_NEXT_PREVIEW,
        PLAYBACK_AUTO_SKIP_CREDITS,
        PLAYBACK_AUTO_SKIP_INTRO,
        PLAYBACK_AUTO_SKIP_RECAP,
        PLAYBACK_SHOW_FORCED_SUBTITLES,
        PLAYER_DOLBY_VISION_ENABLED,
        PLAYER_DV_PROFILE7_HDR10_FALLBACK,
        PLAYER_HDR_ENABLED,
        PLAYER_MATCH_FRAME_RATE,
        PLAYER_SEEK_CACHE_ENABLED,
        UI_HIGH_CONTRAST,
        UI_REMEMBER_LIBRARY_PAGE_STATE,
    )

    val INT_KEYS: Set<String> = setOf(
        PLAYBACK_MAX_BITRATE_KBPS,
        PLAYBACK_NEXT_UP_PROMPT_SECONDS,
        PLAYER_AUDIO_SYNC_MS,
        PLAYER_SLEEP_TIMER_DEFAULT_MINUTES,
        PLAYER_SUBTITLE_SYNC_MS,
    )

    val DOUBLE_KEYS: Set<String> = setOf(
        PLAYER_PLAYBACK_SPEED,
    )
}

object SettingPresentationMetadata {
    val OPTION_SETS: Map<String, SettingOptionSet> = mapOf(
        "catalog_metadata_languages" to SettingOptionSet(
            type = "language_tag",
            options = listOf(
                SettingSuggestedOption("ar", 1),
                SettingSuggestedOption("bn", 1),
                SettingSuggestedOption("bg", 1),
                SettingSuggestedOption("zh", 1),
                SettingSuggestedOption("hr", 1),
                SettingSuggestedOption("cs", 1),
                SettingSuggestedOption("da", 1),
                SettingSuggestedOption("nl", 1),
                SettingSuggestedOption("en", 1),
                SettingSuggestedOption("fi", 1),
                SettingSuggestedOption("fr", 1),
                SettingSuggestedOption("de", 1),
                SettingSuggestedOption("el", 1),
                SettingSuggestedOption("he", 1),
                SettingSuggestedOption("hi", 1),
                SettingSuggestedOption("hu", 1),
                SettingSuggestedOption("id", 1),
                SettingSuggestedOption("it", 1),
                SettingSuggestedOption("ja", 1),
                SettingSuggestedOption("ko", 1),
                SettingSuggestedOption("ms", 1),
                SettingSuggestedOption("no", 1),
                SettingSuggestedOption("fa", 1),
                SettingSuggestedOption("pl", 1),
                SettingSuggestedOption("pt", 1),
                SettingSuggestedOption("ro", 1),
                SettingSuggestedOption("ru", 1),
                SettingSuggestedOption("sk", 1),
                SettingSuggestedOption("sl", 1),
                SettingSuggestedOption("es", 1),
                SettingSuggestedOption("sv", 1),
                SettingSuggestedOption("ta", 1),
                SettingSuggestedOption("te", 1),
                SettingSuggestedOption("th", 1),
                SettingSuggestedOption("tr", 1),
                SettingSuggestedOption("uk", 1),
                SettingSuggestedOption("vi", 1),
            ),
        ),
        "playback_audio_languages" to SettingOptionSet(
            type = "language_tag",
            options = listOf(
                SettingSuggestedOption("ar", 1),
                SettingSuggestedOption("bn", 1),
                SettingSuggestedOption("bg", 1),
                SettingSuggestedOption("zh", 1),
                SettingSuggestedOption("hr", 1),
                SettingSuggestedOption("cs", 1),
                SettingSuggestedOption("da", 1),
                SettingSuggestedOption("nl", 1),
                SettingSuggestedOption("en", 1),
                SettingSuggestedOption("fi", 1),
                SettingSuggestedOption("fr", 1),
                SettingSuggestedOption("de", 1),
                SettingSuggestedOption("el", 1),
                SettingSuggestedOption("he", 1),
                SettingSuggestedOption("hi", 1),
                SettingSuggestedOption("hu", 1),
                SettingSuggestedOption("id", 1),
                SettingSuggestedOption("it", 1),
                SettingSuggestedOption("ja", 1),
                SettingSuggestedOption("ko", 1),
                SettingSuggestedOption("ms", 1),
                SettingSuggestedOption("no", 1),
                SettingSuggestedOption("fa", 1),
                SettingSuggestedOption("pl", 1),
                SettingSuggestedOption("pt", 1),
                SettingSuggestedOption("ro", 1),
                SettingSuggestedOption("ru", 1),
                SettingSuggestedOption("sk", 1),
                SettingSuggestedOption("sl", 1),
                SettingSuggestedOption("es", 1),
                SettingSuggestedOption("sv", 1),
                SettingSuggestedOption("ta", 1),
                SettingSuggestedOption("te", 1),
                SettingSuggestedOption("th", 1),
                SettingSuggestedOption("tr", 1),
                SettingSuggestedOption("uk", 1),
                SettingSuggestedOption("vi", 1),
            ),
        ),
        "playback_subtitle_languages" to SettingOptionSet(
            type = "language_tag",
            options = listOf(
                SettingSuggestedOption("ar", 1),
                SettingSuggestedOption("bn", 1),
                SettingSuggestedOption("bg", 1),
                SettingSuggestedOption("zh", 1),
                SettingSuggestedOption("hr", 1),
                SettingSuggestedOption("cs", 1),
                SettingSuggestedOption("da", 1),
                SettingSuggestedOption("nl", 1),
                SettingSuggestedOption("en", 1),
                SettingSuggestedOption("fi", 1),
                SettingSuggestedOption("fr", 1),
                SettingSuggestedOption("de", 1),
                SettingSuggestedOption("el", 1),
                SettingSuggestedOption("he", 1),
                SettingSuggestedOption("hi", 1),
                SettingSuggestedOption("hu", 1),
                SettingSuggestedOption("id", 1),
                SettingSuggestedOption("it", 1),
                SettingSuggestedOption("ja", 1),
                SettingSuggestedOption("ko", 1),
                SettingSuggestedOption("ms", 1),
                SettingSuggestedOption("no", 1),
                SettingSuggestedOption("fa", 1),
                SettingSuggestedOption("pl", 1),
                SettingSuggestedOption("pt", 1),
                SettingSuggestedOption("ro", 1),
                SettingSuggestedOption("ru", 1),
                SettingSuggestedOption("sk", 1),
                SettingSuggestedOption("sl", 1),
                SettingSuggestedOption("es", 1),
                SettingSuggestedOption("sv", 1),
                SettingSuggestedOption("ta", 1),
                SettingSuggestedOption("te", 1),
                SettingSuggestedOption("th", 1),
                SettingSuggestedOption("tr", 1),
                SettingSuggestedOption("uk", 1),
                SettingSuggestedOption("vi", 1),
            ),
        ),
    )

    val DEFINITIONS: Map<String, SettingPresentation> = mapOf(
        SettingKeys.CATALOG_METADATA_LANGUAGE to SettingPresentation(
            suggestedOptions = "catalog_metadata_languages",
            unsetLabel = "Library default",
        ),
        SettingKeys.PLAYBACK_AUDIO_LANGUAGE to SettingPresentation(
            suggestedOptions = "playback_audio_languages",
            unsetLabel = "No preference",
        ),
        SettingKeys.PLAYBACK_SUBTITLE_LANGUAGE to SettingPresentation(
            suggestedOptions = "playback_subtitle_languages",
            unsetLabel = "None",
        ),
    )

    fun suggestedValues(key: String, revision: Int = SettingKeys.REVISION): List<String> {
        val setId = DEFINITIONS[key]?.suggestedOptions ?: return emptyList()
        return OPTION_SETS[setId]?.options
            ?.filter { it.introducedIn <= revision }
            ?.map { it.value }
            .orEmpty()
    }
}
